# Generated by Django 5.0.6 on 2024-06-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='postcode',
            field=models.IntegerField(null=True),
        ),
    ]
